### ISSUE TITLE
I get an error message when installing/uninstalling translucentflyouts

### ISSUE THREAD

**Issue by Dhyfer1** [ALTaleX531/TranslucentFlyouts#41] opened 2023-08-08 15:57 UTC
Hi @ALTaleX531 

I have followed the steps to install translucentflyouts, but every time i run the bat file (as admin and without admin) to install/uninstall this error message you see in the image always appears, and there is no visible change in the menus 

![image_5.png](https://github.com/ALTaleX531/TranslucentFlyouts/assets/50301201/b79d834a-a63e-46c7-be5f-7f93872ed4a4)

This happens in Windows 11 Pro latest dev build

**Comment by ALTaleX531** [comment] 2023-08-09 02:10
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/e3616987-6e56-46de-b2d5-ef2167bae8f2)
It works fine in my Windows 11 Canary Build 25921, so I guess some of your system components was corrupted...

**Comment by Dhyfer1** [comment] 2023-08-09 11:15
> It works fine in my Windows 11 Canary Build 25921, so I guess some of your system components was corrupted...

I don't know if it's like you say. Is there a way to send you a log about this problem? I forgot to say that I used before [AcrylicMenus](https://github.com/krlvm/AcrylicMenus), but i uninstalled it before using translucentflyouts

**Comment by ALTaleX531** [comment] 2023-08-09 14:45
Please go to `System > About`, and copy the ` Windows specifications` to me.

**Comment by Dhyfer1** [comment] 2023-08-09 15:26
I send you a screenshot of my windows specs

![Screenshot 2023-08-09 102017.png](https://github.com/ALTaleX531/TranslucentFlyouts/assets/50301201/15065654-b4ef-46f6-9171-caaa00143780)

**Comment by ALTaleX531** [comment] 2023-08-11 15:22
I just installed the last dev build of Windows, but it works fine except there is a bug that task scheduler doesn't execute specific commands automatically.
So, I suggest you to download the TranslucentFlyouts again or reinstall Windows.

**Comment by Dhyfer1** [comment] 2023-08-12 03:56
Hmm. I have installed the latest version, but I still have the same problem. I will reinstall Windows and let you know if that was the solution.

**Comment by Dhyfer1** [comment] 2023-08-13 02:29
Hi again.

I have reinstalled Windows dev channel from scratch, but still have the same problem. :'( I don't understand why I can't run translucentflyouts, instead AcrylicMenus which is based on translucentflyouts does work without problem. And I don't understand what is the cause of the error shown in the image and how to fix it. 😢

**Comment by ALTaleX531** [comment] 2023-08-13 03:41
I have adjusted the compile options, please try this build.
[TranslucentFlyoutsV2.x64.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12328754/TranslucentFlyoutsV2.x64.zip)

If this build is still not working, please try to disabled your anti-virus software temporarily.

**Comment by Dhyfer1** [comment] 2023-08-13 20:45
Nothing. I have downloaded the version from the link, but still appear the same error message, even disabling the antivirus I can't get translucentflyouts to work. 😥

**Comment by ALTaleX531** [comment] 2023-08-15 14:09
Emm, I have no idea how to solve it...

**Comment by Dhyfer1** [comment] 2023-08-18 13:07
I have no idea either, I don't understand why it's not working. As I said before, AcrylicMenus is based on translucentflyouts, but AcrylicMenus does work without any problem.

Why isn't it working? Maybe some key is missing from the registry? or does translucentflyouts need a specific version of the .net framework, .net core or visual studio redistributable? or i don't have some dll file that translucentflyouts needs?

**Comment by ALTaleX531** [comment] 2023-08-18 16:03
This program does not need any .net framework/core and visual studio redistributable.
From your image, it seems an error occured while executing `LoadLibraryExW` but I still don't know why.
Have you ever tried the beta.2 version yet?

**Comment by Dhyfer1** [comment] 2023-08-18 23:56
> Have you ever tried the beta.2 version yet?

Of course. I have used the latest beta version, but it hasn't fixed that error, I still get the same message. It seems that it was a problem of some missing or unregistered dll file, I don't know. 🙁

**Comment by ALTaleX531** [comment] 2023-08-25 15:21
Please try this build...😢
[TranslucentFlyoutsV2.x64.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12440883/TranslucentFlyoutsV2.x64.zip)

**Comment by Dhyfer1** [comment] 2023-08-30 01:42
> Please try this build...😢 [TranslucentFlyoutsV2.x64.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/12440883/TranslucentFlyoutsV2.x64.zip)

I have tried it, and also the latest version 2.1.0, but it has not solved my issue yet. In the readme of your project, there is a note for the installation that says:

> [Note!]:   
> **Downloading symbol files from Microsoft server is required at the first time or after a windows update, otherwise some functionalities will be unavailable!**

When I run the install.bat or uninstall.bat file (as admin, or without admin) a command window opens showing only the text `"C:\Windows\System32>start Rundll32 C:\Program Files\TranslucentFlyoutsV2.x64\TFMain64.dll",Main /install` and in less than a second this command window closes, and then the error message that I have already shown in this issue appears.

Here is a [video](https://imgur.com/a/ruTwRU9) where you can see that the command window closes quickly, and it does not look like it is downloading anything.

**Comment by ALTaleX531** [comment] 2023-08-31 12:12
Well...🤔
Are you using a clean Windows from MSDN? I tested it in 5 different machines but I still can't reproduce this error, so my suggestion is that please try to install a clean Windows in a separate disk. This error really appears to be caused by missing system components.😢

**Comment by Dhyfer1** [comment] 2023-09-01 11:03
> Are you using a clean Windows from MSDN? I tested it in 5 different machines but I still can't reproduce this error, so my suggestion is that please try to install a clean Windows in a separate disk. 

From MSDN? I do not know what you mean. I download the ISO for the latest dev version of windows 11 from [here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso) and then I mount it with Rufus on my unsupported PC. Maybe translucent flyouts doesn't work on an unsupported Windows 11 PC?  All your 5 machines they are compatible?

Yesterday I reinstalled windows 11 again, on my main drive and on another partition, but I have the same problem. 🙁

**Comment by Dhyfer1** [comment] 2023-09-02 00:10
> Well, let me do a small test, can you execute this command successfully? `rundll32.exe shell32.dll,Control_RunDLL ` If yes, it will open a control panel, otherwise it will reproduce the error message you have shown before.

Yes, after executing the command the Control Panel appears as you said, no error dialog appears after that.

> I will mark this issue as a unique one and never close it until I am able to reproduce it. Once I successfully reproduce it, I will solve it as soon as possible. 

Thanks for taking my problem into account. It seems that I am the only user to whom this happens, too bad, I hope you can find a solution.

> Before then, I think you have to use AcrylicMenus...😢

Yeah, I have been using AcrylicMenus for a long time. I already knew TranslucentFlyouts from the first version but I never used it, because I have always used AcrylicMenus. But now that the dev of AcrylicMenus is going to abandon the project as mentioned in his repository and recommends to use TranslucentFlyouts that has more features, I decided to try TranslucentFlyouts, but I find this problem why I created this issue.

So, in the meantime, I'm afraid I'll have to keep using AcrylicMenus. 😞

**Comment by bbmaster123** [comment] 2023-09-15 18:09
I get this issue as well on all systems that don't have visual studio installed, both windows 10 and 11
If I install VS and compile myself, TFMain64 installs and runs fine, but If I move the self-compiled files to a new system without VS, it will fail to install with the same error as OP

edit:
Fixed by including the C++ Runtime in output directory in configuration properties > advanced.
hope that helps, and hopefully this will be resolved in the next major release 
cheers :)

**Comment by Dhyfer1** [comment] 2023-09-15 20:17
@bbmaster123 Can you tell me step by step how you did it? What should I install for translucentflyouts to work? I'm not an advanced user so I don't know anything about compiling something.

**Comment by Dhyfer1** [comment] 2023-09-15 20:17
@bbmaster123 Can you tell me step by step how you did it? What should I install for translucentflyouts to work? I'm not an advanced user so I don't know anything about compiling something.

**Comment by bbmaster123** [comment] 2023-09-15 21:25
@Dhyfer1 
do you plan to build from source? 
If not, I'm happy to zip up the 14 or so dll's and post them here
Its as simple as dropping the files into the TranslucentFlyouts folder and running install.bat as admin

**Comment by Dhyfer1** [comment] 2023-09-15 21:58
> @Dhyfer1 
> do you plan to build from source? 

As I said before, I don't know anything about compiling code, much less building from source, I'm a newbie 😅

> If not, I'm happy to zip up the 14 or so dll's and post them here
> Its as simple as dropping the files into the TranslucentFlyouts folder and running install.bat as admin

I think it's a good idea. Thx. On my PC I still can't run translucentflyouts and I think your files would be of help to me, until @Maplespe releases a new version that I hope will solve my problem taking into account your previous comment.

So I'm waiting for your files. Thank you.

**Comment by Dhyfer1** [comment] 2023-09-15 21:59
> @Dhyfer1 
> do you plan to build from source? 

As I said before, I don't know anything about compiling code, much less building from source, I'm a newbie 😅

> If not, I'm happy to zip up the 14 or so dll's and post them here
> Its as simple as dropping the files into the TranslucentFlyouts folder and running install.bat as admin

I think it's a good idea. Thx. On my PC I still can't run translucentflyouts and I think your files would be of help to me, until @Maplespe releases a new version that I hope will solve my problem taking into account your previous comment.

So I'm waiting for your files. Thank you.

**Comment by bbmaster123** [comment] 2023-09-15 22:43
no worries, here's the runtime files from visual studio https://github.com/bbmaster123/FWFU/raw/main/TFv2-Runtimes.zip

hope it works for you :)

**Comment by Dhyfer1** [comment] 2023-09-15 23:05
Thanks for the link 😊 but it's down 🙁

**Comment by Dhyfer1** [comment] 2023-09-15 23:06
Thanks for the link 😊 but it's down 🙁

**Comment by ALTaleX531** [comment] 2023-09-16 04:01
@bbmaster123 
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/288afc6c-ad56-42e6-ae34-1790be768685)
However, TranslucentFlyouts does not rely on C++ Runtime at all, and it works fine in my brand new OS.

**Comment by bbmaster123** [comment] 2023-09-16 18:10
that's odd, my OS was brand new as well, downloaded from microsoft's media creation tool.
if translucentflyouts doesn't rely on C++ Runtime, I don't understand why that works for me?
I tried to narrow it down to a single file on the OS without visual studio, but it only successfully installs when all dlls are present...

**Comment by Dhyfer1** [comment] 2023-09-17 01:27
@bbmaster123 I'm sorry to say that your solution has not worked for me 😥 I copied the 14 files into the translucentflyouts folder, then ran the install.bat file as admin but the error message still appears, even after a fresh install of Windows. What is the problem?

I was wondering that maybe it could work if I built translucentflyouts from source like you did, but like I said before I have no idea about this.

Or do I have to have some runtime installed for it to work?

**Comment by SanekGamer007** [comment] 2023-09-17 18:18
i have the same thing on windows 10 2009

**Comment by Eurothopia** [comment] 2023-10-18 18:55
mhm so I got the same thing over here (22H2, freshly reset)
and I dug up something from event viewer:
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/90931142/fdcd293c-60d2-43b7-b1ad-7a3d2f56ac78)

```Faulting application name: rundll32.exe_TFMain64.dll, version: 10.0.19041.3570, time stamp: 0x534b7e9f
Faulting module name: TFMain64.dll, version: 0.0.0.0, time stamp: 0x64eb92bb
Exception code: 0xc000001d
Fault offset: 0x0000000000008d7b
Faulting process id: 0x3798
Faulting application start time: 0x01da01f280912e21
Faulting application path: C:\WINDOWS\system32\rundll32.exe
Faulting module path: C:\Users\lehie\runtimes\TranslucentFlyouts\TFMain64.dll
Report Id: 11035098-8760-4b21-8238-b35ac8900bf0
Faulting package full name: 
Faulting package-relative application ID: 
```

and then another instantly following error:
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/90931142/2af36974-52b0-4725-a2c4-7a77239725c0)
```Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Windows host process (Rundll32) because of this error.

Program: Windows host process (Rundll32)
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0
```

but then like
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/90931142/7bb3e8ae-5bad-4db7-9b3d-301294c78d9b)
doesn't really make sense imo

**Comment by Eurothopia** [comment] 2023-10-18 18:58
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/90931142/01ea8c09-eb3c-407b-9ae4-3b3cd3951894)
dunno

**Comment by ALTaleX531** [comment] 2023-11-24 13:37
TranslucentFlyouts mainly relies on Task Scheduler to run at startup. I think maybe your anti-virus software prevent TF from running at startup...

**Comment by ALTaleX531** [comment] 2024-03-06 12:50
I finally realized that your CPU probably doesn't support the enhanced instruction set, I think I should be able to fix it soon.

**Comment by Dhyfer1** [comment] 2024-03-06 12:59
> I finally realized that your CPU probably doesn't support the enhanced instruction set, I think I should be able to fix it soon.

Is what you say for me or someone else in this post? If it's for me, perfect, I'm still waiting for a solution.

**Comment by ALTaleX531** [comment] 2024-03-09 10:54
I think it has been fixed in the latest version.

**Closed by ALTaleX531** 2024-03-09 10:54 UTC
Labels: help wanted, cannot reproduce

**Comment by Dhyfer1** [comment] 2024-03-10 14:44
> I think it has been fixed in the latest version.

That's right. Thank you very much!, translucentflyouts is now running smoothly on my PC. I've been wanting to try your app for a long time and now I can, I'm happy because it's finally working. 😃
