### ISSUE TITLE
TF hates PowerToys, or vice versa

### ISSUE THREAD

**Issue by MuscularPuky** [ALTaleX531/TranslucentFlyouts#112] opened 2024-03-11 09:22 UTC
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/93962018/810ed6e8-ee6e-4ccc-b338-95b06ce0f189)

Unfortunetely there's 23 splited zips. plz welcome them kindly, and remove .text suffix 23 times
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.zip.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556212/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.zip.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z06.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556214/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z06.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z05.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556217/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z05.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z04.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556221/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z04.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z03.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556223/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z03.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z02.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556224/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z02.txt)
[PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z01.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556225/PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z01.txt)
[PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.zip.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556229/PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.zip.txt)
[PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z04.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556232/PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z04.txt)
[PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z03.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556235/PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z03.txt)
[PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z02.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556240/PowerToys.PowerAccent.exe-minidump-2024-03-11-17-45-03.z02.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z01.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556243/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z01.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.zip.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556244/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.zip.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z09.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556245/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z09.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z08.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556247/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z08.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z07.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556249/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z07.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z06.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556251/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z06.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z05.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556252/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z05.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z04.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556253/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z04.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z03.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556256/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z03.txt)
[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z02.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556257/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-45-33.z02.txt)

[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z07.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556209/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z07.txt)

[PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z01.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14556208/PowerToys.PowerLauncher.exe-minidump-2024-03-11-17-44-34.z01.txt)

**Comment by ALTaleX531** [comment] 2024-03-11 10:05
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/105535231/b4d7e733-9cfb-4c5e-a088-894cba93bfb9)
Thanks for the feedback, you can temporarily add the PowerToys component to the exclusion list manually to prevent crashes, as shown in the image. I'll check out what went wrong later.

**Comment by TechySC23** [comment] 2024-03-11 10:06
I was just about to comment

**Comment by TechySC23** [comment] 2024-03-11 10:08
What's Power Launcher? I use PowerToys and there's not even a single thing! (Except power accent). And even I use PowerToys but it doesn't happen to me! What version of TF are you running @MuscularPuky?

**Comment by TechySC23** [comment] 2024-03-11 10:09
Seems that PT (PowerToys) conflicts with it @ALTaleX531

**Comment by ALTaleX531** [comment] 2024-03-11 13:06
[TranslucentFlyouts.Win32.V3.x64.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/14558984/TranslucentFlyouts.Win32.V3.x64.zip)
Please check if this build solves the issue.

**Comment by TechySC23** [comment] 2024-03-11 15:37
@ALTaleX531 Look at this, I was just tinkering with the GUI with some normal settings and suddenly this showed up:
![image](https://github.com/ALTaleX531/TranslucentFlyouts/assets/138615236/2c6ed7f4-c4fb-4fc3-8792-c9478648f835)

**Comment by TechySC23** [comment] 2024-03-11 15:38
The GUI suddenly closed too. It's the same error as the OP. Also I found that Power Launcher.exe is PowerToys Run

**Comment by ALTaleX531** [comment] 2024-03-11 16:28
@TechySC23 Can you also upload your dump file? I've gotten some crash clues, but I need further confirmation.

**Comment by Satanarious** [comment] 2024-03-11 18:19
How do you reproduce this error?

**Comment by ALTaleX531** [comment] 2024-03-11 18:29
@Satanarious Here are the steps I took to reproduce the error
1. Switch to the "Global" tab.
2. Change the "Effect Type".
3. Click the "Apply" button.
4. Click the "Apply" button again.
5. Click the "x" button

**Comment by Satanarious** [comment] 2024-03-11 18:33
This error is on TF v3.0, right? Because I have a previous version and it works fine.

**Comment by ALTaleX531** [comment] 2024-03-11 18:39
When I attach the debugger to TFC, TF is not currently running. I think this bug existed a long time ago because closing the window and crashing behave almost the same in front of the user.

**Comment by Satanarious** [comment] 2024-03-11 18:43
Is it crashing on exit or is it somehow hindering the functionality? I mean does everything else work fine besides the crash when you try to close the application?

**Comment by ALTaleX531** [comment] 2024-03-11 18:48
I think it's just crash when closing the app, I didn't find anything else abnormal about it.

**Comment by Satanarious** [comment] 2024-03-11 18:50
But how is Translucent Flyouts catching this error?

**Comment by ALTaleX531** [comment] 2024-03-11 18:55
TF calls the win32 api `SetUnhandledExceptionFilter` and passes in its own top-level exception filter callback function, which would normally be called if the exception was not caught by the application. These exceptions that are not caught by the application will cause the application to crash, and this function is specifically designed to detect abnormal crashes.

**Comment by Satanarious** [comment] 2024-03-11 18:59
That explains it. I'll try to fix it. Please make an issue on my [repo](https://github.com/Satanarious/TranslucentFlyoutsConfig).

**Comment by TechySC23** [comment] 2024-03-12 13:17
@Satanarious and @ALTaleX531 How is your progress going for the issue? I am not even touching anything in TFC after that problem. And yes ALTaleX531 the steps to reproduce are somewhat correct. I remember changing the effect type and all the animation effects using TFC. Sadly the dump file is a whopping 323 MB so I can't upload it. I even tried 7Zip, the planet's best compressing software 🤣, choosing the Ultra compression and maxing out (Not really because sadly my laptop only has about 8 GB), it only came to about 52 MB which is an insane compression, but the max file size for GitHub is 25MB so I really CAN'T 😔.

**Comment by TechySC23** [comment] 2024-03-12 13:22
The issue is NOT "TFC will crash if you close the window after changing and applying settings in the Global tab." It is: TFC will throw an error after the user changes some effects and settings. Why not globally? In my case I changed not the global tab but the Menu and the Tooltip tab.

**Comment by TechySC23** [comment] 2024-03-12 13:28
Wait, PT crash? no PT didn't crash while this threw at me (error).

**Comment by ALTaleX531** [comment] 2024-03-12 13:33
@TechySC23 Oh well never mind, I thought the PowerToys crash also happened to you. So can you upload your TFC dump file?

**Comment by ALTaleX531** [comment] 2024-03-12 13:36
> 以及您在这个问题上的进展如何？在这个问题之后，我什至没有碰过 TFC 中的任何东西。是的，ALTaleX531，重现的步骤在某种程度上是正确的。我记得使用 TFC 更改了效果类型和所有动画效果。可悲的是，转储文件高达 323 MB，所以我无法上传它。我什至尝试了 7Zip，地球上最好的压缩软件🤣，选择超压缩并最大化（不是真的，因为可悲的是我的笔记本电脑只有大约 8 GB），它只有大约 52 MB，这是一个疯狂的压缩，但 GitHub 的最大文件大小是 25MB，所以我真的不能😔。

Haven't you tried the new build below? I remembered that I had adjusted the dump settings to prevent garbage data.

> [TranslucentFlyouts.Win32.V3.x64.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/14558984/TranslucentFlyouts.Win32.V3.x64.zip) Please check if this build solves the issue.

**Comment by TechySC23** [comment] 2024-03-12 13:38
No I didn't try it but I did download it. I'll try to upload my dump file. But what's up with your text? It's in Chinese?

**Comment by ALTaleX531** [comment] 2024-03-12 13:42
Oh please forgive stupid MS Edge for automatically translating it again when I quoted it.

**Comment by TechySC23** [comment] 2024-03-12 14:03
what's your mail id? I am gonna mail you directly

**Comment by ALTaleX531** [comment] 2024-03-12 14:07
> what's your mail id? I am gonna mail you directly

2368730049@qq.com

**Comment by TechySC23** [comment] 2024-03-12 15:02
Sent 📤

**Comment by MuscularPuky** [comment] 2024-03-12 15:47
> @TechySC23 You can upload the dump file to Google Drive, but the TFC issue is not that important. I'm now most curious about the steps to reproduce the PowerToys crash, can you tell me how to reproduce it?

It throws exception randomly when PowerToys startsup. I tried on 0.78.0~0.78.x (canary) and it occurs on only 0.79.0+ I think?
I'm trying more case but for some reason TF does not dump anymore in desktop path. While I sleep yesterday our Windows closed my unsaved projects and force updated so I lost all application logs include TF LOL. I'm gonna track this issue again and talk to you bout this soon.

**Comment by ALTaleX531** [comment] 2024-03-12 15:58
@TechySC23 I've looked at the dump file you sent and it seems to be a TFC issue as well, as QT seems to try to read a `QWindows` object with a null pointer.

**Comment by ALTaleX531** [comment] 2024-03-13 06:52
@MuscularPuky 0.79.0+ is the preview version and it's indeed unstable and crashes even when I'm not running TF. The reason I asked how to reproduce it is because those exceptions recorded in those dump files don't appear to be caused by TF.

**Comment by MuscularPuky** [comment] 2024-03-15 09:54
> @MuscularPuky 0.79.0+ is the preview version and it's indeed unstable and crashes even when I'm not running TF. The reason I asked how to reproduce it is because those exceptions recorded in those dump files don't appear to be caused by TF.

uh I think TF hates not only PowerToys but also others
I couldn't send a big file with mail so you should meet split zips again sadly

[Explorer.EXE-minidump-2024-03-13-00-26-56.z01.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613693/Explorer.EXE-minidump-2024-03-13-00-26-56.z01.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613695/Explorer.EXE-minidump-2024-03-13-00-26-56.zip)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z10.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613696/Explorer.EXE-minidump-2024-03-13-00-26-56.z10.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z09.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613698/Explorer.EXE-minidump-2024-03-13-00-26-56.z09.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z08.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613699/Explorer.EXE-minidump-2024-03-13-00-26-56.z08.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z07.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613700/Explorer.EXE-minidump-2024-03-13-00-26-56.z07.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z06.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613701/Explorer.EXE-minidump-2024-03-13-00-26-56.z06.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z05.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613706/Explorer.EXE-minidump-2024-03-13-00-26-56.z05.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z04.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613707/Explorer.EXE-minidump-2024-03-13-00-26-56.z04.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z03.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613708/Explorer.EXE-minidump-2024-03-13-00-26-56.z03.txt)
[Explorer.EXE-minidump-2024-03-13-00-26-56.z02.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613709/Explorer.EXE-minidump-2024-03-13-00-26-56.z02.txt)
[DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.z01.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613711/DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.z01.txt)
[DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.zip](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613713/DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.zip)
[DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.z03.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613714/DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.z03.txt)
[DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.z02.txt](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613715/DevHomeGitHubExtension.exe-minidump-2024-03-15-17-17-38.z02.txt)

This guy's not split
[Explorer.EXE-minidump-2024-03-13-16-53-37.dmp](https://github.com/ALTaleX531/TranslucentFlyouts/files/14613736/Explorer.EXE-minidump-2024-03-13-16-53-37.dmp)

**Comment by ALTaleX531** [comment] 2024-03-15 10:37
You should not use TranslucentFlyouts.Immersive, its code has may problems and it is not ready for use.

**Comment by TechySC23** [comment] 2024-03-15 12:06
@ALTaleX531 TFC Crashed again after installing your version (v3.0.1). Want to know what I did? Well said no and kept TF!

**Comment by TechySC23** [comment] 2024-03-15 12:18
@ALTaleX531 I did upgrade to that (v3.0.1). Also, I complained to Satanarious about this crash. Did he release a new version?

**Comment by TechySC23** [comment] 2024-03-15 12:19
Yep he did

**Comment by ALTaleX531** [comment] 2024-03-18 16:29
The PowerToys issue can already be solved by adding the process name to the DisabledList, so the issue is obsolete , closing it now.

**Closed by ALTaleX531** 2024-03-18 16:29 UTC
Labels: question
