### ISSUE TITLE
EnableCustomRendering crashes Registry Editor

### ISSUE THREAD

**Issue by e-t-l** [ALTaleX531/TranslucentFlyouts#46] opened 2023-08-09 04:26 UTC
When `Computer\HKEY_CURRENT_USER\Software\TranslucentFlyouts\Menu\EnableCustomRendering` = `1`, right-clicking anywhere in Registry Editor causes the application to hang and then crash.

--
v2.0.0-alpha.4
Windows 11 Home version 22000

**Comment by ALTaleX531** [comment] 2023-08-09 04:30
Duplicate of #40

**Closed** 2023-08-09 05:00 UTC
Labels: bug, duplicate
